<?php

namespace App\Jobs;

use App\Models\Resume;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Queue\Queueable;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Storage;
use Illuminate\Http\File;

class UploadResumeToStorage implements ShouldQueue
{
    use Queueable;

    /**
     * Create a new job instance.
     */
    public function __construct(
        public string $tempFilePath,
        public Resume $resume
    ) {}

    /**
     * Execute the job.
     */
    public function handle(): void
    {
        Log::info("Starting resume upload for Resume ID: {$this->resume->id}");

        try {
            // 1. Upload to Supabase
            // We need to re-create the filename logic or pass it.
            // The resume filename was already decided in controller, let's reuse the basename relative to storage
            // Actually, in the controller we create a filename.
            // Let's verify what we stored in DB. We stored 'fileUri' but it might be a placeholder.
            // Let's generate a unique filename here or use the one from the temp file if unique.

            // Re-reading the plan: "Update the Resume record with fileUri and publicUrl"
            // So we can generate the final path here.

            $filename = basename($this->tempFilePath); // Use the temp filename which should be unique enough (generated by tempnam or UUID in controller)

            // To be safe and consistent with previous logic, let's append .pdf if missing or just trust the controller
            // Controller generated: $filename = Str::uuid() . '_' . time() . '.pdf';
            // We should ideally pass the desired filename to this job or just use the temp one.

            $file = new File($this->tempFilePath);
            $path = Storage::disk('supabase')->putFileAs(
                'resumes',
                $file,
                $file->getFilename(),
                'public'
            );

            if (!$path) {
                throw new \Exception("Failed to upload file to Supabase");
            }

            // 2. Generate Public URL
            $projectUrl = env('PROJECT_URL');
            $bucketName = env('SUPABASE_BUCKET');
            $publicUrl = "{$projectUrl}/storage/v1/object/public/{$bucketName}/{$path}";

            // 3. Update Resume Record
            $this->resume->update([
                'fileUri' => $path,
                'publicUrl' => $publicUrl,
            ]);

            Log::info("Resume uploaded for Resume ID: {$this->resume->id}. Path: {$path}");

            // 4. Delete Local Temp File
            if (file_exists($this->tempFilePath)) {
                unlink($this->tempFilePath);
                Log::info("Deleted local temp file: {$this->tempFilePath}");
            }

        } catch (\Exception $e) {
            Log::error("Failed to upload resume for Resume ID: {$this->resume->id}. Error: " . $e->getMessage());
            // Retry? Or fail.
            // If we fail here, the file stays on server (not good) but eventually we might clear temp.
        }
    }
}
